#!/usr/bin/env bash
set -e

echo "Resetting webppl to latest remote..."
cd assets/webppl
git fetch origin
git reset --hard origin/master

echo "Compiling latest remote (and committing if changed)..."
browserify -t brfs src/main.js > compiled/webppl.js
if [[ `git status --porcelain` ]];
then
   echo "Compilation resulted in changes, committing webppl..."
   git add compiled/webppl.js
   git commit -m "Updated compiled version"
   git push origin master
else
   echo "Compilation found no changes, skipping webppl commit..."
fi

cd ../..
if [[ `git status --porcelain` ]];
then
   echo "Submodule changed, committing dippl..."
   git commit assets/webppl -m "Updated webppl submodule"
   git push origin gh-pages
else
   echo "Submodule unchanged, skipping dippl commit..."
fi

echo "Done!"
